[project]
name = "hibiki"
version = "0.1.0"
requires-python = ">=3.13"
description = "A language specifically to make writing musical tabs easier and more fun."
authors = [
    {name = "Taira", email = "tairabiteru@users.noreply.github.com"}
]